# Perform continuous integration tests on updates and pull requests
name: Build Firmware
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup cache
      uses: actions/cache@v4
      with:
        path: ci_cache
        key: ${{ runner.os }}-build-${{ hashFiles('scripts/ci-install.sh') }}
        restore-keys: |
          ${{ runner.OS }}-build-

    - name: Prepare build
      run: ./scripts/ci-install.sh

    - name: Build
      run: ./scripts/ci-build.sh 2>&1

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: ci_build/output
